-- ==========================================
-- SUPABASE SETUP SCRIPT FOR RSA PORTAL & WEBSITE
-- ==========================================
-- This script sets up all tables, relations, indexes, storage buckets, 
-- triggers, and Row Level Security (RLS) policies required for the application.
-- Run this script in the Supabase SQL Editor.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. DATABASE TABLES (PUBLIC SCHEMA)
-- ==========================================

-- Test Table
CREATE TABLE IF NOT EXISTS public.test (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Images Table
CREATE TABLE IF NOT EXISTS public.images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    url TEXT NOT NULL
);

-- Gallery Table
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    image TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Instagram Posts Table
CREATE TABLE IF NOT EXISTS public.instagram_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image TEXT NOT NULL,
    likes INT DEFAULT 0,
    comments INT DEFAULT 0,
    post_link TEXT,
    post_date DATE,
    caption TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    category TEXT NOT NULL,
    location TEXT,
    year TEXT,
    area TEXT,
    photographer TEXT,
    client TEXT,
    hero_image TEXT NOT NULL,
    description TEXT NOT NULL,
    images TEXT[] DEFAULT ARRAY[]::TEXT[],
    content JSONB DEFAULT '[]'::jsonb,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    youtube_walkthrough_heading TEXT,
    youtube_walkthrough_link TEXT,
    featured BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Testimonials Table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT,
    company TEXT,
    image TEXT,
    rating INT DEFAULT 5,
    text TEXT NOT NULL,
    featured BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Careers / Jobs Table
CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    department TEXT,
    location TEXT,
    type TEXT,
    description TEXT NOT NULL,
    requirements TEXT[] DEFAULT ARRAY[]::TEXT[],
    responsibilities TEXT[] DEFAULT ARRAY[]::TEXT[],
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Employees Table (Public Portfolio Team Section)
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    imageurl TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Employee Profiles Table (Employee Portal)
CREATE TABLE IF NOT EXISTS public.employee_profiles (
    id SERIAL PRIMARY KEY,
    auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    employee_id TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL,
    approval_status TEXT DEFAULT 'pending' CHECK (approval_status IN ('pending', 'approved', 'rejected')),
    disabled BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Salary Components Table
CREATE TABLE IF NOT EXISTS public.salary_components (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('earning', 'deduction')),
    attendance_based BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Employee Salary Structure (Bridge Table)
CREATE TABLE IF NOT EXISTS public.employee_salary_structure (
    id SERIAL PRIMARY KEY,
    employee_profile_id INT REFERENCES public.employee_profiles(id) ON DELETE CASCADE,
    component_id INT REFERENCES public.salary_components(id) ON DELETE CASCADE,
    amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (employee_profile_id, component_id)
);

-- Attendance Records Table
CREATE TABLE IF NOT EXISTS public.attendance_records (
    id SERIAL PRIMARY KEY,
    employee_profile_id INT REFERENCES public.employee_profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    check_in_time TIMESTAMPTZ DEFAULT now(),
    status TEXT DEFAULT 'present' CHECK (status IN ('present', 'absent', 'half_day', 'late')),
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (employee_profile_id, date)
);

-- Payslips Table
CREATE TABLE IF NOT EXISTS public.payslips (
    id SERIAL PRIMARY KEY,
    employee_profile_id INT REFERENCES public.employee_profiles(id) ON DELETE CASCADE,
    month TEXT NOT NULL, -- Format: YYYY-MM
    basic_salary DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    hra DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    travel_allowance DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    bonus DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    pf_deduction DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    tax_deduction DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    other_earnings DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    other_deductions DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    custom_components JSONB DEFAULT '{}'::jsonb,
    total_present_days NUMERIC(4, 1) NOT NULL DEFAULT 0.0,
    total_working_days INT NOT NULL,
    gross_salary DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    total_deductions DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    net_salary DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (employee_profile_id, month)
);


-- ==========================================
-- 2. SEED DEFAULT DATA
-- ==========================================

-- Seed default Salary Components
INSERT INTO public.salary_components (name, type, attendance_based) VALUES
    ('Basic Salary', 'earning', true),
    ('HRA', 'earning', false),
    ('Travel Allowance', 'earning', true),
    ('Bonus', 'earning', false),
    ('PF Deduction', 'deduction', false),
    ('Tax Deduction', 'deduction', false)
ON CONFLICT (name) DO NOTHING;


-- ==========================================
-- 3. STORAGE BUCKETS (images)
-- ==========================================

-- Create the images bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;


-- ==========================================
-- 4. AUTH TRIGGER FOR AUTO-CREATING PROFILES
-- ==========================================

-- Create/replace trigger function for handling new auth user registration
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    new_employee_id TEXT;
BEGIN
    -- Derive a default/custom employee ID from metadata, or fallback to UUID snippet
    new_employee_id := COALESCE(
        new.raw_user_meta_data->>'employee_id', 
        'RSA-' || UPPER(SUBSTRING(new.id::text FROM 1 FOR 8))
    );

    INSERT INTO public.employee_profiles (
        auth_user_id,
        full_name,
        email,
        phone,
        employee_id,
        role,
        approval_status,
        disabled
    ) VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'full_name', 'Employee'),
        new.email,
        new.raw_user_meta_data->>'phone',
        new_employee_id,
        COALESCE(new.raw_user_meta_data->>'role', 'Employee'),
        'pending',
        false
    );
    
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind the trigger function to the auth.users table
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ==========================================
-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable Row Level Security (RLS) for all tables
ALTER TABLE public.test ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instagram_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.salary_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_salary_structure ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payslips ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------
-- RLS: Public Tables (Projects, Gallery, etc.)
-- ------------------------------------------

-- Allow public read access to everyone
CREATE POLICY "Public Read Projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Public Read Gallery" ON public.gallery FOR SELECT USING (true);
CREATE POLICY "Public Read Instagram Posts" ON public.instagram_posts FOR SELECT USING (true);
CREATE POLICY "Public Read Testimonials" ON public.testimonials FOR SELECT USING (true);
CREATE POLICY "Public Read Jobs" ON public.jobs FOR SELECT USING (true);
CREATE POLICY "Public Read Employees" ON public.employees FOR SELECT USING (true);
CREATE POLICY "Public Read Images" ON public.images FOR SELECT USING (true);
CREATE POLICY "Public Read Test" ON public.test FOR SELECT USING (true);

-- Allow writes to portfolio tables
-- SECURITY NOTE: The admin panel (/youcantseeme) makes client-side updates using the Supabase client
-- with the Anon Key (without a Supabase auth login). To keep it functioning, these policies 
-- allow direct writes. 
-- In a strictly secured production environment, you should transition the admin panel to utilize 
-- Supabase Auth and change the ALL policies below from "TO public" / "USING (true)" to "TO authenticated".
CREATE POLICY "Admin Write Projects" ON public.projects FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin Write Gallery" ON public.gallery FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin Write Instagram Posts" ON public.instagram_posts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin Write Testimonials" ON public.testimonials FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin Write Jobs" ON public.jobs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin Write Employees" ON public.employees FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin Write Images" ON public.images FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin Write Test" ON public.test FOR ALL USING (true) WITH CHECK (true);

-- ------------------------------------------
-- RLS: Employee Portal (Secure Tables)
-- ------------------------------------------

-- Note: Server Actions (Prisma) run with admin/superuser permissions, bypassing RLS.
-- These policies secure direct client-side reads by logged-in employees.

-- Employee Profiles
CREATE POLICY "Employees can read own profile" ON public.employee_profiles
    FOR SELECT TO authenticated USING (auth.uid() = auth_user_id);

CREATE POLICY "Employees can update own profile" ON public.employee_profiles
    FOR UPDATE TO authenticated USING (auth.uid() = auth_user_id) WITH CHECK (auth.uid() = auth_user_id);

-- Salary Components
CREATE POLICY "Authenticated users can read salary categories" ON public.salary_components
    FOR SELECT TO authenticated USING (true);

-- Salary Structure
CREATE POLICY "Employees can read own salary structure" ON public.employee_salary_structure
    FOR SELECT TO authenticated USING (
        employee_profile_id IN (
            SELECT id FROM public.employee_profiles WHERE auth_user_id = auth.uid()
        )
    );

-- Attendance Records
CREATE POLICY "Employees can read own attendance" ON public.attendance_records
    FOR SELECT TO authenticated USING (
        employee_profile_id IN (
            SELECT id FROM public.employee_profiles WHERE auth_user_id = auth.uid()
        )
    );

-- Payslips
CREATE POLICY "Employees can read own payslips" ON public.payslips
    FOR SELECT TO authenticated USING (
        employee_profile_id IN (
            SELECT id FROM public.employee_profiles WHERE auth_user_id = auth.uid()
        )
    );

-- ------------------------------------------
-- RLS: Storage Bucket Policies (images)
-- ------------------------------------------

-- Enable read access to the images bucket for everyone
CREATE POLICY "Public Read Images Bucket" ON storage.objects
    FOR SELECT USING (bucket_id = 'images');

-- Enable upload/insert access for public/authenticated users to the images bucket
CREATE POLICY "Allow Upload Images Bucket" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'images');

-- Enable delete access to the images bucket
CREATE POLICY "Allow Delete Images Bucket" ON storage.objects
    FOR DELETE USING (bucket_id = 'images');
